---
- hosts: all
  become: true
  roles:
    - base

- hosts: poll_groups
  become: true
  roles:
    - poll

- hosts: postgres_groups
  become: true
  roles:
    - postgres

- hosts: redis_groups
  become: true
  roles:
    - redis

- hosts: result_groups
  become: true
  roles:
    - result
    
- hosts: worker_groups
  become: true
  roles:
    - worker