---
#- hosts: all
#  become: true
#  roles:
#    - base

- hosts: result_group
  become: true
  roles:
    - result

- hosts: poll_group
  become: true
  roles:
    - poll

#- hosts: postgres_group
#  become: true
#  roles:
#    - postgres

#- hosts: redis_group
#  become: true
#  roles:
#    - redis

- hosts: worker_group
  become: true
  roles:
    - worker