---
  - name: copy file to remote host
    copy: 
      src: ./worker.tar
      dest: /tmp
      mode: 0755

  - name: Unarchive a file that is already on the remote machine
    unarchive:
      src: /tmp/worker.tar
      dest: /home/
      remote_src: yes