---
  - name: copy file to remote host
    copy: 
      src: ./poll.tar
      dest: /tmp
      mode: 0755

  - name: copy file to remote host
    copy: 
      src: ./roles/poll/files/poll.service
      dest: /etc/systemd/system/
      mode: 0755

  - name: Unarchive a file that is already on the remote machine
    unarchive:
      src: /tmp/poll.tar
      dest: /home/
      remote_src: yes

  - name: Make sure the dependencies are installed
    pip:
      requirements: /home/poll/requirements.txt

  - name: Make sure a service is running
    systemd:
      name: poll
      enabled: yes

  - name: Make sure a service is running
    systemd:
      name: poll
      state: started
      