- name: Make sure the dependencies are installed
  apt:
    pkg:
      - "python3-psycopg2"
      - "locales"
    state: present
    update_cache: yes

- name: Install Postgres
  apt:
    name:
      - "postgresql"
      - "postgresql-client"
      - "postgresql-contrib"
    state: present
    update_cache: yes